version: '2.0'
services:
  registry:
    image: registry:2.7
    ports:
      - 5000:5000
    volumes:
      - /home/infrausr/docker-registry-ui-std/registry-data:/var/lib/registry
      - /home/infrausr/docker-registry-ui-std/registry-config/credentials.yml:/etc/docker/registry/config.yml
      - /home/infrausr/docker-registry-ui-std/registry-config/htpasswd:/etc/docker/registry/htpasswd

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=Docker-Registry-UI
      - REGISTRY_URL=http://localhost:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
